### ISSUE TITLE
Enforce apache user

### ISSUE THREAD

**Issue by lucasdiedrich** [Turgon37/docker-glpi#2]
Enforce apache user is the owner of the mountable volumes, once you mount /var/www/files for example it gave me the error below for the installation:

![image](https://user-images.githubusercontent.com/817482/35095361-55071fe2-fc2f-11e7-9358-3fe7aa9b8c84.png)
Command to reproduce: 
```bash
docker run -d --restart=unless-stopped -v /volumes/glpi/data:/var/www/files -p [::1]:8680:80 turgon37/glpi
```

If you wan't i can help you with the issues that i'm opening.

**Comment by Turgon37** [comment]
Hi,
It's a bit complicated, because you have made a docker host mount. First, I think it's a bad practice, in particular because of theses chmod/own issues. And then as you can see, the folder /var/www/files/ already contains some almost empty folders that are not automatically copied in your host mount path /volumes/glpi/data

So, to conclude, imagine you have badly mount the folder /var/www/files, for example in a wrong location on your NAS server or anywhere. If I set a chmod/own in the Docker /start.sh entrypoint, I will possibly edit permissions of all folder/files tree inside your NAS/share instead of simply raise an error as on your screenshots.

I can propose you to add this feature with a configuration variables available in the docker environment, so by default it will be disabled, and you will be able to enable it.

Regards

**Comment by Turgon37** [comment]
I've updated the GLPI image to 9.2.1 and added an environment variable GLPI_CHMOD_PATHS_FILE that you must set to 'yes' to perform a chmod/chown on glpi start.

Could you test and make a feedback please ?

**Comment by Turgon37** [comment]
Any news here ?

**Comment by Turgon37** [comment]
I suppose this is fixed because I've not any news
